version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  django-tools: pennlabs/django-tools@0.0.2
  helm-tools: pennlabs/helm-tools@0.1.7

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master
jobs:
  check:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: mysql://root:password@127.0.0.1:3306/circle_test
      - image: circleci/mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: circle_test
      - image: circleci/redis:latest

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - django-tools/setup
      - django-tools/lint:
          black: false
      - run:
          name: Run tests
          command: |
            mkdir test-results
            pipenv run nose2 -c setup.cfg --with-coverage --plugin nose2.plugins.junitxml
      - django-tools/code-coverage
      - django-tools/upload-artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - check:
          context: labs-api-server
      - docker/publish:
          requires:
            - check
          cache_from: "pennlabs/labs-api-server:latest"
          image: pennlabs/labs-api-server
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - docker/publish
          context: k8s-deploy
          <<: *branch-filters
